model_params:    
  encoder:

    first:
      kernel: 3
      stable_layers: 1
      padding: 1
      stride: 1
      fan_in: 3
      fan_out: 3

    second:
      kernel: 3
      stable_layers: 1
      padding: 1
      stride: 1
      fan_in: 3
      fan_out: 3

    third:
      kernel: 3
      stable_layers: 1
      padding: 1
      stride: 1
      fan_in: 3
      fan_out: 3


  decoder:

    first:
      kernel: 3
      stable_layers: 1
      padding: 1
      stride: 1
      fan_in: 3
      fan_out: 3

    second:
      kernel: 3
      stable_layers: 1
      padding: 1
      stride: 1
      fan_in: 3
      fan_out: 3

    third:
      kernel: 3
      stable_layers: 1
      padding: 1
      stride: 1
      fan_in: 3
      fan_out: 3
  
 



