data:
  root_dir: "/home/kunet.ae/100053688/datastore/ViT"
  csv_dir: "/home/kunet.ae/100053688/datastore/csv-files/joined-data.csv"
  out_dir: "/home/kunet.ae/100053688/out/hpc_tasks_ae/trail_1/"
  batch_size: 64
  train_shuffle: True
  test_shuffle: False
  train_split:  0.7
  test_split:  0.3
  


params:
  no_epoch: 1000
  save_fre: 1
  LR: 0.001
  LR: 0.0001
  LR: 0.00001
  LR: 0.0000001
  
  

hparams:
  initial_image_size: 576
  kernel: 3
  





Train:

Test:

hydra:
 output_subdir: null
 run:
  dir: .













