data:
  root_dir: "/home/kunet.ae/100053688/datastore/ViT"
  csv_dir: "/home/kunet.ae/100053688/datastore/csv-files/joined-data.csv"
  batch_size: 4
  train_shuffle: True
  test_shuffle: False
  train_split:  0.7
  test_split:  0.3

hparams:
  initial_image_size: 576
params:
  no_epoch: 10
  print_fre: 1
  LR: 0.001
  device:




hydra: 
 output_subdir: null  
 run:  
  dir: .










